### PR TITLE
Ch code coverage setup 162414265

### PR DESCRIPTION
**Pull request by ebzeal**
#### What does this PR do?

 - Sets up Code Coverage using Code Climate

#### Description of Task to be completed?

 - Connect test from the Neon-ah Repository to Code climate
 - Configure .travis.yml file
 - Install a test suite(mocha) nyc and mocha-lcov-reporter

#### How should this be manually tested?
 - Run test code from package.json

#### What are the relevant pivotal tracker stories?
 - [Integrate Coveralls code coverage service](https://www.pivotaltracker.com/n/projects/2229851/stories/162414265)

### CODE REVIEW

**Comment by profmcdan** [comment]
Resolve merge conflicts

**Review by profmcdan — CHANGES_REQUESTED** [review]
Review merge conflicts

**Comment by ebzeal** [comment]
Resolved merge conflicts

**Review by profmcdan — APPROVED** [review]
Looks good.

**Pull request merged**
