### PR TITLE
#162414274 CRUD article ratings

### PR DESCRIPTION
**Pull request by Bobsar0**
#### What does this PR do?
Perform CRUD operation on Article Ratings

#### Description of Task to be completed?
 • Create RatingsController class functionality
 • Create `createOrUpdateRatings` method in the controller to handle creation of ratings if non-existent and updating of existent ratings
 • Create rating route functionality
 • Setup tests

#### How should this be manually tested?
• Clone this branch
• cd into the repo
• run npm install
• run npm test

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/162414274

### CODE REVIEW

**Comment by ebzeal** [comment]
You still have conflicting files, please rebase

**Comment by rafmme** [comment]
LGTM, yet

**Comment by tejiri4** [comment]
LGTM, yet

**Comment by Sammuel09** [comment]
LGTM, yet

**Comment by ebzeal** [comment]
LGTM yet

**Pull request merged**
