### PR TITLE
#162414255 Integrate Github to Slack

### PR DESCRIPTION
**Pull request by tejiri4**
#### What does this PR do?
This PR integrate github repository to slack channel neon-bots

#### Description of Task to be Completed?
-  Install github app on slack
- Install slack on github
- Integrate github to slack

#### How should this be manually tested?
Does not require testing

#### What are the relavant pivotal tracker stories?
[Linking Github to Slack](https://www.pivotaltracker.com/story/show/162414255)

### CODE REVIEW

**Comment by rafmme** [comment]
```Looks good to me```

**Comment by Makwe-O** [comment]
Looks good to me

**Review by profmcdan — CHANGES_REQUESTED** [review]
Fix merge conflicts

**Comment by profmcdan** [comment]
Merge conflict resolved in the readme.md file

**Pull request merged**
